Update docs to new standards and development environment to NTC stand…
nautobot/nautobot-plugin-nornir pull request #63
Opened 2022-09-05 02:50 UTC by itdependsnetworks

…ards

2022-09-05 15:48 UTC, cmsirbu commented on README.md
> +  <img src="./images/icon-NautobotPluginNornir.png" class="logo" height="200px">
```suggestion
  <img src="https://raw.githubusercontent.com/nautobot/nautobot-plugin-nornir/develop/docs/images/icon-NautobotPluginNornir.png" class="logo" height="200px">
```
I missed this in the cookie, image URL must be absolute so it also works in the docs site landing page.

2022-09-05 15:53 UTC, itdependsnetworks commented on README.md
> +  <img src="./images/icon-NautobotPluginNornir.png" class="logo" height="200px">
yea, a little bit of a catch 22, when rendering locally, this doesn't work until merged. I would prefer to keep a "TODO" in here.

2022-09-05 22:11 UTC, itdependsnetworks commented on README.md
> +  <img src="./images/icon-NautobotPluginNornir.png" class="logo" height="200px">
Understood, just doing it this way as I am testings.

2022-09-07 08:06 UTC, ubajze requested changes

2022-09-07 08:06 UTC, ubajze commented on .github/workflows/ci.yml
> +          repo_token: "${{ secrets.NTC_GITHUB_TOKEN }}"
@itdependsnetworks I think we should keep the `GH_NAUTOBOT_BOT_TOKEN`

2022-09-07 13:36 UTC, itdependsnetworks commented on docs/user/app_feature_credentials.md
> +TODO: Verify `pluginx`
@jeffkala

2022-09-07 17:35 UTC, jeffkala commented on docs/user/app_feature_credentials.md
> +TODO: Verify `pluginx`
What is the ask here? `pluginx` could be any other nornir plugin.  for example `"pyntc.extras.secret"`

2022-09-09 19:13 UTC, jeffkala approved these changes

2022-09-09 19:13 UTC, merged